### ISSUE TITLE
Crawler not triggered in manual deploys

### ISSUE THREAD

**Issue by arinthros** [algolia/algoliasearch-netlify#157]
The crawler does not seem to be triggering for manual deploys. Any thoughts on how to get it to trigger? I'm not seeing the crawler item in the deploy summary, but the plugin is showing up in the plugins list.

We run a docker process in Gitlab to build a static site, then use the `netlify-cli` npm package to deploy the files.

**gitlab-ci.yml**
```yml
- npm run build
- npm i -g netlify-cli
- netlify deploy --dir build --prod
```

**netlify.toml**
```toml
[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['production']
  renderJavaScript = true
```

**Netlify deploy details**
![Screen Shot 2020-12-17 at 3 15 06 PM](https://user-images.githubusercontent.com/6694199/102544809-f8d79d80-407a-11eb-9b54-36452a5d91ff.png)
